# ===================================================================
# Standard Spring Boot properties
# ===================================================================
project:
  version: @project.version@

server:
  port: 8080
  tomcat:
    accesslog:
      directory: logs/minid-notification-server/
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
    redirect-context-root: false
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
    encoding:
      force: true
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  forward-headers-strategy: NATIVE

# Spring boot actuator endpoint
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health, version, info, prometheus"
  info:
    git:
      mode: full

cache:
  internal-id: notification-service
  local:
    ttl-in-s: 120
  cluster:
    ttl-in-s: 300
    transport:
      file-location: cache-transport.xml
infinispan:
  embedded:
    enabled: true


springdoc:
  show-actuator: true
  oAuthFlow:
    authorizationUrl: https://eid-systest-web01.dmz.local/idporten-oidc-provider/authorize
    tokenUrl: https://eid-systest-web01.dmz.local/idporten-oidc-provider/token
  cache:
    disabled: true
  swagger-ui:
    oauth:
      client-id:
      client-secret:
      scopes:

spring:
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false

  # Spring Security - OAuth 2 provider
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://eid-systest-web01.dmz.local/idporten-oidc-provider/
        opaquetoken:
          introspection-uri: https://eid-systest-web01.dmz.local/idporten-oidc-provider/tokeninfo
          client-id: test_rp_systest
          client-secret: password

  datasource:
    url: jdbc:mysql://eid-systest-db01.dmz.local:3306/minid_notification?useMysqlMetadata=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: minid_notif
    password: password
#    type: org.apache.tomcat.jdbc.pool.DataSource
    type: com.zaxxer.hikari.HikariDataSource # for tomcat use: org.apache.tomcat.jdbc.pool.DataSource
    hikari:
      maximum-pool-size: 5
      auto-commit: false
      register-mbeans: true
      max-lifetime: 540000
      leak-detection-threshold: 30
    tomcat:
      max-active: 5
      min-idle: 5
      default-auto-commit: false

  flyway:
    validate-on-migrate: false
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

# ===================================================================
# Application specific properties
# ===================================================================
digdir:
  app-versions:
    ios:
      latest: "1.2.3"
      required: "1.0"
    android:
      latest: "2.0.2"
      required: "1"

  firebase:
    credentials-json: classpath:firebase-credentials.json
    notification-image-url: https://idporten.difi.no/error/images/svg/eid.svg
  google-api:
    sandbox: true
    bundle-id: no.digdir.minid.authenticator
    auth-key: YOUR_API_KEY
  proxy:
    enabled: false
    host: localhost
    port: 3128
    skip-hosts: oidc-test1.difi.eon.no|localhost
  authenticator:
    expiry: 180
    app-identifier: no.digdir.minid.authenticator
    priority: normal
    ttl: 180
    onboarding-category: onboardingCategory
    authentication-aps-category: auth_category
    authentication-click-action: minid_auth_intent
  audit:
    log-dir: logs/minid-notification-server/audit
    log-file: audit-log.json
  minid-backend-service:
    url: http://eid-systest-otf-app01.dmz.local:10010
  minid-authentication-service:
    url: https://eid-systest-web01.dmz.local/minid-authentication

mock:
  notification:
    enabled: false

#  # Event config
#  event:
#    jms-url: tcp://localhost:40002
#    jms-queue: logqueue
