version: '3.3'

services:
  minid-notification-server:
    image: ${REGISTRY}/minid-notification-server:${VERSION}
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  minid-notification-db:
    image: ${REGISTRY}/minid-notification-db:${VERSION}
    configs:
      - log_config
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    ports:
      - 3306
    networks:
      atest:
    command: --sql_mode=""
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-oidc-provider:
    image: eid-jenkins02.dmz.local:8082/idporten-oidc-provider:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 443
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  oidc-db:
    image: eid-jenkins02.dmz.local:8082/oidc-db:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    ports:
      - 3306
    networks:
      atest:
    command: --sql_mode=""
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  oidc-client-db:
    image: eid-jenkins02.dmz.local:8082/oidc-client-db:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    ports:
      - 3306
    networks:
      atest:
    command: --sql_mode=""
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  eventlog-db:
    image: eid-jenkins02.dmz.local:8082/eventlog-db:latest
    ports:
      - 3306
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    networks:
      atest:
    command: --sql_mode=""
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  opendj:
    image: eid-jenkins02.dmz.local:8082/opendj:latest
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  web:
    image: eid-jenkins02.dmz.local:8082/web:latest
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    ports:
      - 443
    networks:
      atest:
        aliases:
          - eid-atest-web01.dmz.local
          - eid-inttest-web01.dmz.local
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-openam:
    image: eid-jenkins02.dmz.local:8082/idporten-openam:latest
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-oidc-client:
    image: eid-jenkins02.dmz.local:8082/idporten-oidc-client:latest
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  serviceprovider-backend:
    image: eid-jenkins02.dmz.local:8082/serviceprovider-backend:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  serviceprovider-api:
    image: eid-jenkins02.dmz.local:8082/serviceprovider-api:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  kontaktinfo-backend:
    image: eid-jenkins02.dmz.local:8082/kontaktinfo-backend:latest
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  kontaktregister-db:
    image: eid-jenkins02.dmz.local:8082/kontaktregister-db:latest
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  idporten-admin:
    image: eid-jenkins02.dmz.local:8082/idporten-admin:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  activemq:
    image:  rmohr/activemq:5.11.1
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    ports:
      - 61616
      - 8161
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  logwriter:
    image:  eid-jenkins02.dmz.local:8082/logwriter:latest
    extra_hosts:
      - "eid-logstash-app01.dmz.local:10.243.220.151"
    configs:
      - log_config
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  selenium:
    image: selenium/standalone-firefox:3.14.0-europium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444
    networks:
      atest:
        aliases:
          - selenium_host
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true

  altinn-gateway:
    image: eid-jenkins02.dmz.local:8082/altinn-gateway:latest
    configs:
      - log_config
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
networks:
  atest:
    driver: overlay
    attachable: true
configs:
  log_config:
    file: ./log_config
